feat: [DHIS2-9858] update user sync test
dhis2/android-settings-app pull request #102
Opened 2021-11-23 06:09 UTC by Sharmyn28

This PR has:

- update functions to get the number of org units, programs, datasets, and program rules related to a specific user.
- update functions to get metadata and data download size
- fix user search field styles
- fix result table styles

_User search field_
![image](https://user-images.githubusercontent.com/29384664/142978005-05b471d0-2a9a-4fa1-bff2-1610d73948b2.png)

_Test loading_
![image](https://user-images.githubusercontent.com/29384664/142978028-ba13b736-bc7e-4c0f-88e6-94ac90c508f4.png)

_Test result_
![image](https://user-images.githubusercontent.com/29384664/142978076-b5c8984d-79b2-4169-8baf-04765906782b.png)

2021-11-23 15:29 UTC, mediremi commented
I'll be away for two weeks so I'm requesting review from @dhis2/team-platform

2021-11-29 15:06 UTC, amcgee requested changes
Lots of good stuff in here @Sharmyn28 

I found a number of patterns which make the code very difficult to read - I tried to make suggestions for most of them, but there are more which also follow these patterns.  In general, try to remember that:
1. `await` will return the value of the resolved promise, so you can assign that value to a normal variable in the async function and operate on it there, instead of using `then` and assigning a `let` variable
2. It is better to use `const` wherever possible, to avoid accidentally mutating something you don't want to change.
3. `Array.map` will return a new copy of the array with the map function applied to each item.  This is useful because you can then assign the result of `.map` to a new variable and just use that, instead of manually `.push`ing to another array.
4. When *not* assigning the result of a `map` to some other variable, it is better to use `forEach`.  This should generally be avoided as it creates deeply-nested code, but is more correct than using `map` and throwing away the return value.

Please let me know if you have any questions of want to go over any of this with me or someone else on the team!

2021-11-29 15:06 UTC, amcgee commented on src/pages/Synchronization/UserSyncTest/helper.js
> +    })
Better to do this sequentially:

```suggestion
    const ouLists = Promise.all(orgUnitPromises)
    ouLists.forEach(ouList => 
        ouList.forEach(ou => {
            orgUnitSearch.push(ou)
        })
    }
    return uniqBy(orgUnitSearch, 'id').length
```

2021-11-29 18:47 UTC, Sharmyn28 commented on src/pages/Synchronization/UserSyncTest/getData.js
> +                pageSize = limitByProgram
I'm trying to do this: 
```

if (limitByProgram) {
  pageSize = globalLimit.teiDownload
} else {
  pageSize = Math.round(globalLimit.teiDownload / programList.length)
}
```

but using a ternary operator

2021-12-01 19:33 UTC, amcgee commented on src/pages/Synchronization/UserSyncTest/getData.js
> +                pageSize = limitByProgram
Ah I see!  Maybe we could wrap the ternary in parenthesis to make it clearer?  But if prettier automatically removes those that's ok, this is fine as-is - sorry I misread it!

2021-12-01 19:33 UTC, amcgee commented on src/pages/Synchronization/UserSyncTest/getData.js
> +                pageSize = limitByProgram
Same comment as above, sorry I misread this one!

2021-12-01 19:34 UTC, amcgee commented on src/pages/Synchronization/UserSyncTest/queries/syncQueries.js
> +        console.log('Error: ', error)
This is an important one, but I don't think it is new in this PR.  Maybe you can look at this in the future (let me know if you want to discuss) but keep it as-is for now :-)

2021-12-01 19:36 UTC, amcgee approved these changes
Really nice work, the updated `await` lines are much easier to understand!  Thanks!

I'm approving this now - if you want to wrap the ternary operators in parentheses to make that logic clearer, feel free.  And I think we should address the error handling (`console.log` in catch handlers) but I don't think it's new in this PR - if that is true, then it's OK to merge this and address that issue separately 👍 💯

2021-12-01 20:16 UTC, merged